### ISSUE TITLE
load playlist from youtube

### ISSUE THREAD

**Issue by sentinelweb** [sentinelweb/cuer#100]
first merge - ended up spending a lot of time on test and ci setup `Feature/100 youtube playlist` (#125)
- [x] Clear out share activity of media scanning - move to playlist_item_edit
- [x] scan playlist link
- [x] implement YouTupe data API for playlist
- [x] add navigation to share activity (start = scan fragment -> playlist & playlist_item_edit targets & others (channel eventually))
- [x] Move type, platform,platformId, and channel from Config to PlaylistDomain
- [x] make a playlist provider to wrap playlist access - no repos in presenter - made orchestrator
- [x] setup UI testing for fragments (#12 )
- [x] setup CI testing for fragments (#3 )
- [x] remove flkay tests (#68 )

second merge to finish feature
- [x] Add playlist to share and display in share activity
- [ ] ~~make a playlist orchestrator to update from yt and then save to db~~ -> #132
- [x] CRUD operations for playlist mem orch
- [x] CRUD operations for playlist item mem orch
- [x] disable UI items (play, edit)
- [ ] error handling for orchectrator exceptions -> #135
- [x] testing for move and delete operations (updating from flows) 
   - [x] remove playlistItem deletion code from queue - delete in playlistpresenter and update q from flow
- [x] flows from memoryorchestrator
- [x] tests for PlaylistPresenter 
- [x] tests for QueueMediator
- [ ] estimate update cost (over multiple api calls)
- [x] media repository emission
- [x] Save as type youtube 
- [x] (add ui) - icon to indicate playlist type
- [x] warning if paylist already exists
- [ ] fix back behaviour from share (goes to scan frag should exit) -> #135
- [x] check ordering on imported playlist items (seem to be out of order)
- [x] fix up buttons on share activity (for connected and not connected 
    - [x] add barrier so fragments dont run under the buttons)

**Comment by sentinelweb** [comment]
### youtube. data apis
**playlists list:** https://developers.google.com/youtube/v3/docs/playlists
**playlist response:** https://developers.google.com/youtube/v3/docs/playlists
**playlist items list:** https://developers.google.com/youtube/v3/docs/playlistItems/list
**playlist items response**:https://developers.google.com/youtube/v3/docs/playlistItems#resource


### quota
**usage** https://developers.google.com/youtube/v3/getting-started#calculating-quota-usage
**cost** https://developers.google.com/youtube/v3/determine_quota_cost

**Comment by sentinelweb** [comment]
`adb shell am start -a android.intent.action.SEND -n uk.co.sentinelweb.cuer.app/.ui.share.ShareActivity -d https://youtu.be/rtEhFynXRhA`

**Comment by sentinelweb** [comment]
link scanning
watch url params
https://webapps.stackexchange.com/questions/9863/are-the-parameters-for-www-youtube-com-watch-documented

**Comment by sentinelweb** [comment]
test data
yt playlists links:
- https://www.youtube.com/watch?v=bhohDVxm-Q8&list=RDbhohDVxm-Q8
-
