### ISSUE TITLE
update remote service

### ISSUE THREAD

**Issue by sentinelweb** [sentinelweb/cuer#340]
- [x] remove muirk from remote service
- [ ] possibly make a basic html interface - move to new module #441
- [x] try update kotlin - didnt work question asked here: https://kotlinlang.slack.com/archives/C3PQML5NU/p1667063522175259

Todo:

- [x] add multicast to remote server
- [x] UI to show/manage remotes, start/stop/
- [x] generate a GUID for local node if doesnt exist on startup - use this as the identifier for remotes (source: `LOCAL_NETWORK`)
- [ ] save local node config in backup - possibly remote node (without user details) #440
- [x] find a better way to inject the ip address into the: localRepository.getLocalNode()
- [ ] need to encrypt passwords when saving #442
- [x] UI to configure local server
- [x] reply to ping and join via webserver
- [x] make net library to execute web requests
- [ ] configure login and JWT tokens #442
- [ ] save login info locally #442
- [ ] try to configure SSL #442
- [ ] move js/remote to a new module #441
- [x] bug: ui didnt update when server stopped by the notification
- [x] bug: remotes flow is RemotesStoreFactory.remotes cancelling somehow
- [x] wifi lock
- [x] auto start / stop on wifi
- [x] trust wifi network SSID
- [x] align popup menu right on row
- [x] hide remote bottom tab if `CUER_REMOTE_ENABLED` is false
- [x] launch location permission from hidden ssid (with dialog) (copy `DisplayOverlayPermissionCheck`)
- [x] remove remote start option from settings
- [x] save remotes list and add status connected when node have been received
- [x] bug: `Join` and `Close` messages dont seem to updates the remotes list
- [x] swipe delete remote node
- [ ] add dont autostart option on notification if enabled #440
- [ ] send  `Join` and `Close` messages via server too to all known remotes (multicast is a bit unreliable) #440

**Comment by sentinelweb** [comment]
Libraries to add to server:

- [ ] Partial content: https://ktor.io/docs/partial-content.html - for streaming and download of big files.
- [ ] JWT tokens : https://ktor.io/docs/jwt.html - issue tokens to other devices
- [ ] SSL: https://ktor.io/docs/ssl.html
- [ ]

**Comment by sentinelweb** [comment]
created 
#440
#441
#442

**Comment by sentinelweb** [comment]
PR #437
